'use client';
import React from 'react';
//@SHADCNUI
import { DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
//@CUSTOM COMPONENTS
import PreviewPreset from '@/features/editor/components/preview-preset';
//@TYPES
import { CopilotHistory, Preset } from '@/features/editor/types';
type Props = {
    copilotResponse: CopilotHistory['response'];
};

export default function PreviewCopilotResponseModal({ copilotResponse }: Props) {
    const preset: Preset = React.useMemo(() => {
        return {
            name: 'copilot-response',
            type: 'text',
            content: copilotResponse.content,
            stylePerDevice: copilotResponse?.stylePerDevice || {
                desktop: {
                    width: '100%',
                    fontSize: '16px',
                    lineHeight: '100%',
                    color: 'var(--default-text)',
                },
                mobile: {
                    width: '100%',
                    fontSize: '16px',
                    lineHeight: '100%',
                    color: 'var(--default-text)',
                },
                tablet: {
                    width: '100%',
                    fontSize: '16px',
                    lineHeight: '100%',
                    color: 'var(--default-text)',
                },
            },
            globalStyle: false,
        };
    }, [copilotResponse]);

    return (
        <>
            <DialogHeader className="gap-1 space-y-0">
                <DialogTitle>Preview copilot response</DialogTitle>
                <DialogDescription>
                    Preview the content generated by the copilot before applying it to your document.
                </DialogDescription>
            </DialogHeader>
            <div className="mb-6 rounded-lg border-2 border-border p-8">
                <PreviewPreset preset={preset} />
            </div>
        </>
    );
}
